| **ID** | **Name**                 | **Place of Research**               | **Effect**                                                                                                                                                       | **Cost**               | **Age Available** | **Research Time** |
|-------:|--------------------------|-------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------|-------------------|-------------------|
| 1     | Teardrop Shields         | Blacksmith                          | Cataphract: +1 armor; Limitanei: +15% movement speed; Varangian Guard: +15% attack speed                                                                         | 100 Food, 250 Gold     | Castle Age        | 60s               |
| 2     | Expilatores              | Stable / Imperial Hippodrome        | Horseman: +2 damage vs Workers; Killing Workers grants +20 Gold                                                                                                  | 30 Wood, 50 Gold       | Feudal Age        | 20s               |
| 3     | Numeri                   | Stable / Imperial Hippodrome        | Enemies hit by Cataphract Trample take +15% more damage for 12 seconds                                                                                           | 150 Food, 350 Gold     | Imperial Age      | 60s               |
| 4     | Trapezites               | Stable / Imperial Hippodrome        | Scouts grant nearby units +25% torch damage within a 4-tile radius                                                                                                | 30 Wood, 50 Gold       | Feudal Age        | 20s               |
| 5     | Greek Fire Projectiles   | Siege Workshop                      | Counterweight Trebuchets deal +30% damage and cause Greek Fire area-of-effect damage                                                                             | 100 Food, 250 Gold     | Imperial Age      | 60s               |
| 6     | Border Settlements       | House                               | Houses gain +7 Line of Sight and build 500% faster                                                                                                                | 40 Wood, 80 Gold       | Feudal Age        | 20s               |
| 7     | Ferocious Speed          | Barracks                            | Varangian Guard gain +30% movement speed while Berserking                                                                                                        | 100 Food, 250 Gold     | Imperial Age      | 60s               |
| 8     | Heavy Dromon             | Dock                                | Dromons leave a burning area-of-effect; “Man the Sails” cooldown reduced to 20 seconds                                                                           | 200 Wood, 200 Gold     | Imperial Age      | 60s               |
| 9     | Liquid Explosives        | Dock                                | Incendiary Ships deal full damage to all enemies in explosion radius                                                                                             | 150 Wood, 150 Gold     | Castle Age        | 60s               |
| 10    | Veteran Contract         | Mercenary House / Golden Horn Tower | Upgrades Mercenaries to Veteran Mercenaries and unlocks new Mercenaries                                                                                          | 50 Food, 125 Gold      | Castle Age        | 30s               |
| 11    | Elite Contract           | Mercenary House / Golden Horn Tower | Upgrades Veteran Mercenaries to Elite; unlocks third-tier Mercenary units                                                                                        | 300 Food, 700 Gold     | Imperial Age      | 60s               |